//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace criptoCatBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billeteras
    {
        public int id_billetera { get; set; }
        public Nullable<int> id_cuenta { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<decimal> monto_dinero { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        public virtual moneda moneda { get; set; }
    }
}
