//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace criptoCatBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_cotizacion
    {
        public int id_historialcotizacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual moneda moneda { get; set; }
    }
}
