//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace criptoCatBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCriptoCatEntities : DbContext
    {
        public BDCriptoCatEntities()
            : base("name=BDCriptoCatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<billeteras> billeteras { get; set; }
        public virtual DbSet<cuenta> cuenta { get; set; }
        public virtual DbSet<detalle_operacion> detalle_operacion { get; set; }
        public virtual DbSet<moneda> moneda { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_operacion> tipo_operacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuario_operacion> usuario_operacion { get; set; }
    }
}
